# Generated by Django 5.2.6 on 2025-09-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
