# Generated by Django 5.2.6 on 2025-09-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0002_alter_style_options_style_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=20),
        ),
    ]
