# Generated by Django 5.2.6 on 2025-09-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0003_alter_style_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], max_length=20),
        ),
    ]
